### ISSUE TITLE
Upgrading to v3 breaks when using redis cluster

### ISSUE THREAD

**Issue by dfioravanti** [taylorhakes/python-redis-cache#29] opened 2024-01-10 12:03 UTC
Upgrading to v3 triggered a `Error "EVALSHA - all keys must map to the same key slot" when work with redis cluster` for all the insertions that was not happening on v2. I cannot really track down why but it works with v2 but not with v3.

If it makes any difference, I am using `json.dumps(jsonable_encoder(obj), sort_keys=True)` as a cache serializer. Where jsonable_encoder comes from [fastapi](https://fastapi.tiangolo.com/tutorial/encoder/).

**Comment by taylorhakes** [comment] 2024-01-10 15:51
Thanks for the report. This is caused by the change in key names v3. I will roll back the change in v3

**Comment by taylorhakes** [comment] 2024-01-10 16:15
This has been rolled back and fixed in 3.0.1. I will work on adding testing for redis cluster to avoid problems like this in the future.

**Closed as completed** 2024-01-10 16:15 UTC
